### ISSUE TITLE
pytest is not working for "lists" task

### ISSUE THREAD

**Issue by ghost** [alem-classroom/template-python-introduction#1]
according to autograde's log, we can find out that tests are crashing on `delete_elem_from_list()` function  
also i have checked other students repositories and they have the same problem

![](https://user-images.githubusercontent.com/67190741/95688399-af5a7480-0c2b-11eb-8bc4-041c0db0c976.png)

**Comment by atlekbai** [comment]
Exercise description has been fixed.
